<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_TheAlgorithmsPython</name>
   <tag></tag>
   <elementGuidId>91beb9ee-6cd3-463c-ba27-bce892d3d660</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='js-pjax-container']/div/div[3]/div/ul/li/div/h3/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-align-middle</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hydro-click</name>
      <type>Main</type>
      <value>{&quot;event_type&quot;:&quot;search_result.click&quot;,&quot;payload&quot;:{&quot;page_number&quot;:1,&quot;per_page&quot;:10,&quot;query&quot;:&quot;python&quot;,&quot;result_position&quot;:1,&quot;click_id&quot;:63476337,&quot;result&quot;:{&quot;id&quot;:63476337,&quot;global_relay_id&quot;:&quot;MDEwOlJlcG9zaXRvcnk2MzQ3NjMzNw==&quot;,&quot;model_name&quot;:&quot;Repository&quot;,&quot;url&quot;:&quot;https://github.com/TheAlgorithms/Python&quot;},&quot;client_id&quot;:&quot;1028659226.1543336286&quot;,&quot;originating_request_id&quot;:&quot;6D5E:32509:1C549B9:28D16D7:5BFD71C8&quot;,&quot;originating_url&quot;:&quot;https://github.com/search?q=python&quot;,&quot;user_id&quot;:3025577}}</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hydro-click-hmac</name>
      <type>Main</type>
      <value>79ece052846b010ef4e336b5213e3d35c73b9bd9cd200a934419d243ba51168f</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/TheAlgorithms/Python</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TheAlgorithms/Python</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;js-pjax-container&quot;)/div[@class=&quot;container-lg px-md-2 mt-lg-4 clearfix&quot;]/div[@class=&quot;col-12 col-md-9 float-left px-2 pt-3 pt-md-0 codesearch-results&quot;]/div[@class=&quot;px-2&quot;]/ul[@class=&quot;repo-list&quot;]/li[@class=&quot;repo-list-item d-flex flex-column flex-md-row flex-justify-start py-4 public source&quot;]/div[@class=&quot;col-12 col-md-8 pr-md-3&quot;]/h3[1]/a[@class=&quot;v-align-middle&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//div[@id='js-pjax-container']/div/div[3]/div/ul/li/div/h3/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Least recently updated'])[2]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recently updated'])[2]/following::a[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Python'])[4]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <value>//a[contains(@href, '/TheAlgorithms/Python')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//h3/a</value>
   </webElementXpaths>
</WebElementEntity>
